// Code generated by MockGen. DO NOT EDIT.
// Source: repository/formRepo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "forms-service/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFormRepo is a mock of FormRepo interface.
type MockFormRepo struct {
	ctrl     *gomock.Controller
	recorder *MockFormRepoMockRecorder
}

// MockFormRepoMockRecorder is the mock recorder for MockFormRepo.
type MockFormRepoMockRecorder struct {
	mock *MockFormRepo
}

// NewMockFormRepo creates a new mock instance.
func NewMockFormRepo(ctrl *gomock.Controller) *MockFormRepo {
	mock := &MockFormRepo{ctrl: ctrl}
	mock.recorder = &MockFormRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFormRepo) EXPECT() *MockFormRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFormRepo) Create(form *models.Form) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", form)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFormRepoMockRecorder) Create(form interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFormRepo)(nil).Create), form)
}

// Delete mocks base method.
func (m *MockFormRepo) Delete(formId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", formId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFormRepoMockRecorder) Delete(formId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFormRepo)(nil).Delete), formId)
}

// Get mocks base method.
func (m *MockFormRepo) Get(formId string) (*models.Form, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", formId)
	ret0, _ := ret[0].(*models.Form)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFormRepoMockRecorder) Get(formId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFormRepo)(nil).Get), formId)
}

// GetFormSubmission mocks base method.
func (m *MockFormRepo) GetFormSubmission(formId, userId string) (*models.FormSubmission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFormSubmission", formId, userId)
	ret0, _ := ret[0].(*models.FormSubmission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFormSubmission indicates an expected call of GetFormSubmission.
func (mr *MockFormRepoMockRecorder) GetFormSubmission(formId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFormSubmission", reflect.TypeOf((*MockFormRepo)(nil).GetFormSubmission), formId, userId)
}

// Update mocks base method.
func (m *MockFormRepo) Update(formId string, form *models.Form) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", formId, form)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockFormRepoMockRecorder) Update(formId, form interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFormRepo)(nil).Update), formId, form)
}

// UpsertFormSubmission mocks base method.
func (m *MockFormRepo) UpsertFormSubmission(form *models.FormSubmission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertFormSubmission", form)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertFormSubmission indicates an expected call of UpsertFormSubmission.
func (mr *MockFormRepoMockRecorder) UpsertFormSubmission(form interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertFormSubmission", reflect.TypeOf((*MockFormRepo)(nil).UpsertFormSubmission), form)
}
