// Code generated by MockGen. DO NOT EDIT.
// Source: services/forms/formService.go

// Package mocks is a generated GoMock package.
package mocks

import (
	dtos "forms-service/dtos"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFormService is a mock of FormService interface.
type MockFormService struct {
	ctrl     *gomock.Controller
	recorder *MockFormServiceMockRecorder
}

// MockFormServiceMockRecorder is the mock recorder for MockFormService.
type MockFormServiceMockRecorder struct {
	mock *MockFormService
}

// NewMockFormService creates a new mock instance.
func NewMockFormService(ctrl *gomock.Controller) *MockFormService {
	mock := &MockFormService{ctrl: ctrl}
	mock.recorder = &MockFormServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFormService) EXPECT() *MockFormServiceMockRecorder {
	return m.recorder
}

// CreateForm mocks base method.
func (m *MockFormService) CreateForm(req *dtos.Form) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateForm", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateForm indicates an expected call of CreateForm.
func (mr *MockFormServiceMockRecorder) CreateForm(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateForm", reflect.TypeOf((*MockFormService)(nil).CreateForm), req)
}

// DeleteForm mocks base method.
func (m *MockFormService) DeleteForm(formId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteForm", formId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteForm indicates an expected call of DeleteForm.
func (mr *MockFormServiceMockRecorder) DeleteForm(formId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteForm", reflect.TypeOf((*MockFormService)(nil).DeleteForm), formId)
}

// GetForm mocks base method.
func (m *MockFormService) GetForm(formId string, page int) (*dtos.Form, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForm", formId, page)
	ret0, _ := ret[0].(*dtos.Form)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForm indicates an expected call of GetForm.
func (mr *MockFormServiceMockRecorder) GetForm(formId, page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForm", reflect.TypeOf((*MockFormService)(nil).GetForm), formId, page)
}

// GetFormDetails mocks base method.
func (m *MockFormService) GetFormDetails(formId, userId string, page int) (*dtos.FormDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFormDetails", formId, userId, page)
	ret0, _ := ret[0].(*dtos.FormDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFormDetails indicates an expected call of GetFormDetails.
func (mr *MockFormServiceMockRecorder) GetFormDetails(formId, userId, page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFormDetails", reflect.TypeOf((*MockFormService)(nil).GetFormDetails), formId, userId, page)
}

// UpdateForm mocks base method.
func (m *MockFormService) UpdateForm(id string, req *dtos.Form) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateForm", id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateForm indicates an expected call of UpdateForm.
func (mr *MockFormServiceMockRecorder) UpdateForm(id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateForm", reflect.TypeOf((*MockFormService)(nil).UpdateForm), id, req)
}

// UpsertFormDetails mocks base method.
func (m *MockFormService) UpsertFormDetails(req *dtos.FormDetails) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertFormDetails", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertFormDetails indicates an expected call of UpsertFormDetails.
func (mr *MockFormServiceMockRecorder) UpsertFormDetails(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertFormDetails", reflect.TypeOf((*MockFormService)(nil).UpsertFormDetails), req)
}
